apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-ingress-operator
  namespace: openshift-kube-apiserver
subjects:
- kind: ServiceAccount
  name: cloud-ingress-operator
  namespace: openshift-cloud-ingress-operator
roleRef:
  kind: Role
  name: cloud-ingress-operator
  namespace: openshift-kube-apiserver
  apiGroup: rbac.authorization.k8s.io