apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloud-ingress-operator
  namespace: openshift-ingress-operator
rules:
- apiGroups:
  - operator.openshift.io
  resources:
  - ingresscontrollers
  verbs:
  - get
  - list
  - watch
  - patch
  - delete
  - create
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
