apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloud-ingress-operator
  namespace: openshift-machine-api
rules:
- apiGroups:
  - machine.openshift.io
  resources:
  - machines
  - machinesets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
