kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloud-ingress-operator-cluster-config-v1-reader
  namespace: kube-system
  labels:
    owner: cloud-ingress-operator
    owner.namespace: openshift-cloud-ingress-operator
subjects:
- kind: ServiceAccount
  name: cloud-ingress-operator
  namespace: openshift-cloud-ingress-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-config-v1-reader-cio
