apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: cloud-ingress-operator
  namespace: openshift-cloud-ingress-operator
rules:
- apiGroups:
  - config.openshift.io
  resources:
    - infrastructures
    - apiservers
    - dnses
  verbs:
    - list
    - get
    - watch
- apiGroups:
  - config.openshift.io
  resources:
  - apiservers
  verbs:
  - patch
  - update
  - watch