apiVersion: cloudingress.managed.openshift.io/v1alpha1
kind: PublishingStrategy
metadata:
  name: example-publishingstrategy
spec:
  # Add fields here
  defaultAPIServerIngress:
    listening: external
  applicationIngress:
    - listening: external
      default: true
      dnsName: "apps.default1.domain"
      certificate:
        name: foo
        namespace: bar
    - listening: internal
      default: false
      dnsName: "apps2.non-default.domain"
      certificate:
        name: foo
        namespace: bar